Add option to ignore all virtual members
krafs/Publicizer pull request #58
Opened 2022-11-27 08:42 UTC by Cyaminthe

Similarly to `IncludeCompilerGeneratedMembers`, adds optional metadata `IncludeVirtualMembers`.
When it is set to false, all virtual members in the assembly are exempt from publicizing (unless specified explicitly).
The default value is true, to not alter previously expected behaviour.

2022-11-29 19:37 UTC, krafs requested changes
Thanks for the PR! Contributors are always welcome :)

Besides a couple of minor comments, I'd still like some kind of test for this. I realize that the existing tests are bulky and hard to read, but they are better than nothing. If you can add a similar test for IncludeVirtualMembers (e.g. adapting the test for CompilerGeneratedMembers) I'd feel better approving the PR.

Again - thanks for helping out!

2022-11-29 19:37 UTC, krafs commented on README.md
> +However, if there is a lot of protected members you have to override, doing this for all of them can be cumbersome.
typo: if there _are_ a lot of...

2022-11-29 19:37 UTC, krafs commented on src/Publicizer/Publicizer.csproj
> +    <Version>2.1.0</Version>
I appreciate you trying to do as much work as possible in this PR to make it ready for a release, but I think bumping the version should be done separate from the new feature. Please revert, and I'll bump it before release.

2022-11-30 19:51 UTC, Cyaminthe commented
> Besides a couple of minor comments, I'd still like some kind of test for this. I realize that the existing tests are bulky and hard to read, but they are better than nothing. If you can add a similar test for IncludeVirtualMembers (e.g. adapting the test for CompilerGeneratedMembers) I'd feel better approving the PR.

Sure thing. Added a test (and fixed the minor comments).

2022-12-01 18:22 UTC, merged

2022-12-01 18:23 UTC, krafs commented
Thanks! I'll try to release soon.